// a script that gets all the wordLists in word_lists (that don't have .gen.) and combines them into a single file, de-duping the words.
// Output is written to combined.gen.txt
// input list format:
// ---
// word1
// word2
// word3
// ---

import fs from "node:fs";
import path from "node:path";

const wordListsPath = path.join(__dirname, "..", "word_lists");
const wordLists = fs.readdirSync(wordListsPath);

const combined = new Set<string>();

for (const file of wordLists) {
  if (!file.endsWith(".gen.txt")) {
    const words = fs
      .readFileSync(path.join(wordListsPath, file), "utf-8")
      .split("\n");
    for (const word of words) {
      if (word.length > 1) {
        combined.add(word.toLowerCase());
      }
    }
  }
}

const combinedPath = path.join(wordListsPath, "combined.gen.txt");
fs.writeFileSync(
  combinedPath,
  "# Generated by generate_combined_wordlist.ts. Do not edit.\n",
);
fs.writeFileSync(combinedPath, Array.from(combined).toSorted().join("\n"), {
  flag: "a",
});
console.log("Combined word list written to", combinedPath);
